In [ ]:
names_list = ["Sachin", "Anjali", "Bat" , 4 , 5, 65.4]
names_tuple = ("Sachin", "Anjali", "Bat" , 4 , 5, 65.4)
name_age = {
'Amay': 31,
'Rahul': 45,
'Neha': 26
}

In [ ]:
country_capitals = {
    "China": "Beijing",
    "India": "New Delhi",
    "United States": "Washington, D.C.",
    "Indonesia": "Jakarta",
    "Pakistan": "Islamabad",
    "Brazil": "Bras√≠lia",
    "Nigeria": "Abuja",
    "Bangladesh": "Dhaka",
    "Russia": "Moscow",
    "Japan": "Tokyo"
}

list_country = ["India", "SL", "Bangladesh"]
list_capital = ["New Delhi", "Colombo", "Dhakha"]

print(list_country[0])
print(list_capital[0])
print(country_capitals["Russia"])

India
New Delhi
Moscow

In [ ]:
name = ["Amay", "Rahul", "Neha"]
age=   [ 31, 45, 26]

print(name[0], age[0])

print(name[2], age[2])

#Key-value pair
name_age = {
'Amay': 31,
'Rahul': 45,
'Neha': 26
}

print(name_age['Neha'])

In [ ]:
###dictionaries in Python

### 1. Creating a Simple Dictionary
## key : value pair
student = {
    "name": "Sachin",  #key : value pair
    "age": 21,
    "major": "Computer Science",
    }


print(student)

names_list = ["Sachin", "Anjali", "Bat" , 4 , 5, 65.4]
names_tuple = ("Sachin", "Anjali", "Bat" , 4 , 5, 65.4)

print(type(names_list))
print(type(names_tuple))
print(type(student))

In [ ]:
### 2. Accessing Values by Keys

name1 = student["name"]
age = student["age"]
joker = student["major"]
print(name1)
print(age)
print(joker)

In [ ]:
### 3. Adding a New Key-Value Pair

student["graduation_year"] = 2024

print(student)

print(student["graduation_year"])

In [ ]:
### 3. Adding a New Key-Value Pair

student["hobby"] = "Painting"

print(student)

print(student["hobby"])

In [ ]:
### 4. Updating a Value

print("Before the change", student)
student["hobby"] = "Dancing"
student["pincode"] = 881100
student["age"] = 35
student["name"] = 'Virat'
print(student)
print(student["age"])

In [ ]:
### 5. Removing a Key-Value Pair with `del`
print(student)

del student["major"]

print(student)

In [ ]:
### 6. Checking if a Key Exists
print(student)
has_major = "major"  in student
print(has_major)

has_name = "name"  in student
print(has_name)


has_Name = "Name"  in student  #Case sensitive
print(has_Name)

In [ ]:
### 7. Getting the Length of a Dictionary

student["car"] = ""
print(student)
num_keys = len(student)
print(student)
print(num_keys)

In [ ]:
### 8. Using `get()` to Access Values Safely
print(student)

# print(student["name1"])

name = student.get("name3", "Name does not exists")
print(name)

name = student.get("age", "Age does not exists")
print(name)

major = student.get("king") #, "Rainbow")
print(major)

print("Hello")

{'name': 'Virat', 'age': 35, 'graduation_year': 2024, 'hobby': 'Dancing', 'pincode': 881100, 'car': ''}
Name does not exists
35
None
Hello

In [ ]:
### 9. Removing a Key-Value Pair with `pop()`
print(student)
graduation_year = student.pop("graduation_year", "Default value when key does not exist")
print(student)
# print(student.pop("earth"))
print(student.pop("earth", "The Key 'earth' does not exist"))

{'name': 'Virat', 'age': 35, 'hobby': 'Dancing', 'pincode': 881100, 'car': ''}
{'name': 'Virat', 'age': 35, 'hobby': 'Dancing', 'pincode': 881100, 'car': ''}
The Key 'earth' does not exist

In [ ]:
### 10. Iterating Over Keys in a Dictionary
my_list = [1,2,6,3,99,-1]
for i in my_list:
  print(i)

student = {'name': 'Virat', 'age': 35, 'hobby': 'Painting', 'car': ''}

print(student)
for x in student:
    print("Key Read is x = ", x)
    print("     Value: ", student[x]) #print(student[name]) #

1
2
6
3
99
-1
{'name': 'Virat', 'age': 35, 'hobby': 'Painting', 'car': ''}
Key Read is x =  name
     Value:  Virat
Key Read is x =  age
     Value:  35
Key Read is x =  hobby
     Value:  Painting
Key Read is x =  car
     Value:

In [ ]:
### 12. Iterating Over Key-Value Pairs
print(student)

for key in student:
    print(key)

print("*"*25)
for x in student.values():
    print(x)

print("*"*25)
for x, y in student.items():
    print(f"{x}: {y}")


print("*"*25)
print(student)

{'name': 'Virat', 'age': 35, 'hobby': 'Painting', 'car': ''}
name
age
hobby
car
*************************
Virat
35
Painting

*************************
name: Virat
age: 35
hobby: Painting
car:
*************************
{'name': 'Virat', 'age': 35, 'hobby': 'Painting', 'car': ''}

In [ ]:

# You can find a key by its value, but it's not as direct as a standard key lookup.
# Since multiple keys can have the same value, you need to iterate through the dictionary to find a match.

student_scores = {'Niraj': 95, 'Suraj': 88, 'Ramesh': 95, 'Clara': 76}
target_score = 95
found_key = None # Initialize a variable to store the key

print(student_scores['Clara'])
# Use .items() to get both the key and value for each pair
for key, value in student_scores.items():
  if value == target_score:
    found_key = key
    break # Stop the loop once the first match is found

print(f"The score {target_score} belongs to: {found_key}")

76
The score 95 belongs to: Niraj

In [ ]:
original_dict  = {'Niraj': 94, 'Suraj': 88, 'Ramesh': 95, 'Clara': 76}

# Swapping keys and values using dictionary comprehension
swapped_dict = {value: key for key, value in original_dict.items()}

print(f"Original dictionary: {original_dict}")
print(f"Swapped dictionary: {swapped_dict}")

Original dictionary: {'Niraj': 94, 'Suraj': 88, 'Ramesh': 95, 'Clara': 76}
Swapped dictionary: {94: 'Niraj', 88: 'Suraj', 95: 'Ramesh', 76: 'Clara'}

In [ ]:

# You can find a key by its value, but it's not as direct as a standard key lookup.
# Since multiple keys can have the same value, you need to iterate through the dictionary to find a match.

student_scores = {'Niraj': 95, 'Suraj': 88, 'Ramesh': 95, 'Clara': 99}
target_score = 95
found_key = None # Initialize a variable to store the key
all_keys = []

print(student_scores['Clara'])

# Use .items() to get both the key and value for each pair
for key, value in student_scores.items():
  if value == target_score:
    found_key = key
    all_keys.append(key)

print("Hello World")
# print("The score {target_score} belongs to: {found_key}")
print(f"The score {target_score} belongs to: {found_key}")
print(f"All keys having score as {target_score} are {all_keys}")

99
Hello World
The score 95 belongs to: Ramesh
All keys having score as 95 are ['Niraj', 'Ramesh']

In [ ]:

students = {
    1: "Rahul Kumar",
    2: "Priya Sharma",
    3: "Rajat Gupta",
    4: "Aisha Khan",
    5: "Karan Singh",
    6: "Sneha Rao",
    7: "Vishal Mehta",
    8: "Nalini Iyer",
    9: "Rohan Jain",
    10: "Diya Patel"
}

# Access a student's name
print(students[1])  # Output: Rahul Kumar

# Add a new student
students[11] = "Eshaan Khanna"

# Update an existing student's name
students[1] = "Rahul K."

# Remove a student
del students[10]

print(students)

In [ ]:
#JSON

{
    "students": [
        {
            "roll": 1,
            "name": "Rahul Kumar",
            "age": 20,
            "city": "Mumbai"
            "aadhar" : 1234567890
        },
        {
            "roll": 2,
            "name": "Priya Sharma",
            "age": 22,
            "city": "Delhi"
        },
        {
            "roll": 3,
            "name": "Rajat Gupta",
            "age": 21,
            "city": "Bangalore"
        }
    ]
}

In [ ]:
from collections import defaultdict

d = defaultdict(int)  # Default value of int() is 0
print(d)

d['apple'] += 1
print(d['apple'])  # Output: 1
print(d['banana'])  # Output: 0 (default value assigned)
print(d)

defaultdict(<class 'int'>, {})
1
0
defaultdict(<class 'int'>, {'apple': 1, 'banana': 0})

In [ ]:
### 12. Using `collections.defaultdict` for Automatic Dictionary Values

from collections import defaultdict
fruits = ["apple", "banana", "apple", "orange","Pear", "Grapes", "banana", "apple", "Pear", "Grapes"]

fruit_count = defaultdict(int)
print(fruit_count)
for x in fruits:
    fruit_count[x] += 1

print(fruit_count)

defaultdict(<class 'int'>, {})
defaultdict(<class 'int'>, {'apple': 3, 'banana': 2, 'orange': 1, 'Pear': 2, 'Grapes': 2})

In [1]:
### 13. Nested Dictionaries

students = {
    "Alice": {"age": 21, "major": "CS"},
    "Bob": {"age": 22, "major": "Math"},
}

print(students)
print("*"*30)
print(students["Alice"])
print("*"*30)
print(students["Alice"]["age"])
print("*"*30)
print(students["Alice"]["major"])
print("*"*30)

{'Alice': {'age': 21, 'major': 'CS'}, 'Bob': {'age': 22, 'major': 'Math'}}
******************************
{'age': 21, 'major': 'CS'}
******************************
21
******************************
CS
******************************

In [2]:

students = {
    "1": {
        "name": "Rahul Kumar",
        "age": 20,
        "city": "Mumbai"
    },
    "2": {
        "name": "Priya Sharma",
        "age": 22,
        "city": "Delhi"
    },
    "3": {
        "name": "Rajat Gupta",
        "age": 21,
        "city": "Bangalore"
    }
}



print(students)
print("*"*30)
print(students["1"])
print("*"*30)
print(students["1"]["name"])  # Output: Rahul Kumar
print("*"*30)
print(students["2"]["age"])   # Output: 22
print("*"*30)
print(students["1"]["city"])   # Output: Mumbai
print("*"*30)



print(students["2"]["city"])
print(students["3"]["name"])

{'1': {'name': 'Rahul Kumar', 'age': 20, 'city': 'Mumbai'}, '2': {'name': 'Priya Sharma', 'age': 22, 'city': 'Delhi'}, '3': {'name': 'Rajat Gupta', 'age': 21, 'city': 'Bangalore'}}
******************************
{'name': 'Rahul Kumar', 'age': 20, 'city': 'Mumbai'}
******************************
Rahul Kumar
******************************
22
******************************
Mumbai
******************************
Delhi
Rajat Gupta

In [7]:
!python --version

import sys
print(sys.version)

Python 3.12.11
3.12.11 (main, Jun  4 2025, 08:56:18) [GCC 11.4.0]

In [6]:
### 15. Merging Two Dictionaries (Python 3.9+)
!python --version

dict1 = {"a": 1, "b": 2}
dict2 = {"b": 3, "c": 4}
merged_dict = dict1 | dict2

print(merged_dict)

merged_dict = dict2 | dict1

print(merged_dict)

Python 3.12.11
{'a': 1, 'b': 3, 'c': 4}
{'b': 2, 'c': 4, 'a': 1}

In [9]:
### 16. Using `setdefault()` to Set a Default Value
student = {
    "name": "Sachin",  #key : value pair
    "age": 21,
    "major": "Computer Science",
    }

student.setdefault("minor", "HSC")

print(student)
print(student['minor'])

{'name': 'Sachin', 'age': 21, 'major': 'Computer Science', 'minor': 'HSC'}
HSC

In [10]:
student["minor"] = "Drawing"
print(student["minor"])

Drawing

In [11]:
### 17. Dictionary Comprehension

squares = {x: x**2 for x in range(1, 6)}
squares

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

In [12]:
### 18. Creating a Dictionary from Two Lists

keys = ["name", "age", "major", "height"]
values = ["Ramesh", 23, "Physics"]
student = dict(zip(keys, values))
print(student)

{'name': 'Ramesh', 'age': 23, 'major': 'Physics'}

In [14]:
### 19. Sorting a Dictionary by Keys

sorted_student = dict(sorted(student.items()))
print(sorted_student)

{'age': 23, 'major': 'Physics', 'name': 'Ramesh'}